# NOTE: the available commands are subject to change between major (meaning 0.x) releases.
# If this config can't be loaded because of an incompatibility, move it to a backup location
# and restart `tongo` to generate a new config

# TODO: explainers for all of these :)

[keys]
# nav_up = "up"
# nav_down = "down"
# nav_left = "left"
# nav_right = "right"

# focus_up = "K"
# focus_down = "J"
# focus_left = "H"
# focus_right = "L"

# create_new = "N"
# edit = "E"
# confirm = "enter"
# reset = "R"
# refresh = "r"
# expand_collapse = " "

# next_page = "n"
# previous_page = "p"
# first_page = "P"
# last_page = "N"

# delete = "D"
# back = "esc"
# quit = "q"

# insert_doc = "I"
# edit_doc = "E"
# duplicate_doc = "C"
# delete_doc = "D"
# yank = "y"

# new_tab = "T"
# next_tab = "]"
# previous_tab = "["
# close_tab = "X"
# duplicate_tab = "S"

# goto_tab_1 = "1"
# goto_tab_2 = "2"
# goto_tab_3 = "3"
# goto_tab_4 = "4"
# goto_tab_5 = "5"
# goto_tab_6 = "6"
# goto_tab_7 = "7"
# goto_tab_8 = "8"
# goto_tab_9 = "9"
