# NOTE: the available commands are subject to change between major (meaning 0.x) releases.
# If this config can't be loaded because of an incompatibility, move it to a backup location
# and restart `tongo` to generate a new config

# TODO: explainers for all of these :)

[keys]
# nav-up = "up"
# nav-down = "down"
# nav-left = "left"
# nav-right = "right"

# focus-up = "K"
# focus-down = "J"
# focus-left = "H"
# focus-right = "L"

# create-new = "A"
# edit = "E"
# confirm = "enter"
# reset = "R"
# refresh = "r"
# expand-collapse = " "

# next-page = "n"
# previous-page = "p"
# first-page = "P"
# last-page = "N"

# delete = "D"
# back = "esc"
# quit = "q"

# duplicate-doc = "C"
# yank = "y"

# new-tab = "T"
# next-tab = "]"
# previous-tab = "["
# close-tab = "X"
# duplicate-tab = "S"

# goto-tab-1 = "1"
# goto-tab-2 = "2"
# goto-tab-3 = "3"
# goto-tab-4 = "4"
# goto-tab-5 = "5"
# goto-tab-6 = "6"
# goto-tab-7 = "7"
# goto-tab-8 = "8"
# goto-tab-9 = "9"
