name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: tongo

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: tongo

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            dependencies: "gcc"
            artifact_name: tongo

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross_arch: true
            artifact_name: tongo

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: tongo.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: matrix.dependencies
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.dependencies }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release --target ${{ matrix.target }}
          use-cross: ${{ matrix.cross_arch }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          case ${{ matrix.target }} in
          *-pc-windows-*)
            7z -y a tongo-${{ matrix.target }}.zip tongo.exe
            sha256sum tongo-${{ matrix.target }}.zip > tongo-${{ matrix.target }}.sha256
            ;;
          *)
            tar czvf tongo-${{ matrix.target }}.tar.gz tongo
            shasum -a 256 tongo-${{ matrix.target }}.tar.gz > tongo-${{ matrix.target }}.sha256
            ;;
          esac;

      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/${{ matrix.artifact_name }}
          asset_name: tongo-${{ matrix.target }}
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
