name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      env:
        cache-name: ci

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy

    - name: Print Installed Components
      run: rustup show

    - name: Build 
      run:  cargo build

    - name: Run Tests
      run: just test

    - name: Clippy
      run: cargo clippy

    - name: Test Install
      run: cargo install --path "." --force --locked
